### ISSUE TITLE
Unable to buy 10-th auto rotating bee 🐝

### ISSUE THREAD

**Issue by moritzlerch** [markxoe/ich-bin-eine-biene-mobile#1]
Despite of having earned enough money to buy da thing I‘m unable to buy the upgrade. 

![B0FBBBFA-6081-4EF8-AE01-05A92DA2693A](https://user-images.githubusercontent.com/59474941/103139481-eabdf880-46dc-11eb-8fad-e49123aa6b58.png)

**Comment by markxoe** [comment]
Oh, em that's unfortunate isn't it.
I'll have to take a look at it tomorrow lol

**Comment by moritzlerch** [comment]
Would be great, thanks!

**Comment by markxoe** [comment]
Ja ok 9 plus 1 ist Hald größer gleich 10, wow Mark, patch kommt bald
