### ISSUE TITLE
Daten verschwinden

### ISSUE THREAD

**Issue by lolKingJojo** [markxoe/ich-bin-eine-biene-mobile#12]
Wenn man das spiel Ganz schließt und dann neu aufmachen sind alle gesammelten saltos (und Upgrades weg).

**Comment by NuiceT** [comment]
War bei mir auch grad so

**Comment by markxoe** [comment]
Hand aufs Herz, habt ihr versucht zu cheaten? #5

**Comment by lolKingJojo** [comment]
> Hand aufs Herz, habt ihr versucht zu cheaten? #5

Ja, aber den bot auf 1 Sekunde gestellt also so schnell wie man in echt auch tippt

**Comment by markxoe** [comment]
Augrund der Struktur und Technik des Codes, kann ich leider nicht gewährleisten, dass alle Autoklicker damit funktionieren. Es gibt ein paar die funktionieren, aber leider nicht alle.
Ist das bei @NuiceT  auch so?

**Comment by nibor91** [comment]
@lolKingJojo wenn wir schon bei der Warheit sind... das waren nicht alle Cheat versuche oder? ;)

**Comment by NuiceT** [comment]
Ich habe tatsächlich nicht gecheated

**Comment by markxoe** [comment]
Ein Bug wurde gefunden und der Patch ist gerade in der Beta Version zum überprüfen.
Ich schließe den Issue, falls es wieder Probleme geben sollte, öffnet es einfach wieder
