### ISSUE TITLE
Neues Update Fehler 

### ISSUE THREAD

**Issue by ghost** [markxoe/ich-bin-eine-biene-mobile#19]
Seit dem neuen Update habe ich 200 multiplier verloren und auch 200 Bienen... 
ebenso mit dem Geld...

**Comment by markxoe** [comment]
Gefixt in 0.13.4

**Comment by ghost** [comment]
Ja habe das geupdated und dann war alles weg

**Comment by markxoe** [comment]
In 0.13.3 wurden keine Daten gespeichert, deshalb können diese nicht wiederhergestellt werden

**Comment by ghost** [comment]
🥺
