### ISSUE TITLE
Punktanzeige 

### ISSUE THREAD

**Issue by Ferdie9000** [markxoe/ich-bin-eine-biene-mobile#25]
Ich fände es schön wenn mann bei Informationen oder wo anders die Punktzahl sehen könnte z.B.
Ne Biene bringt 1 punkt und so weiter

**Comment by LKrumme** [comment]
Hab eingekauft und danach wieder meinen Punktestand angeguckt: Biene 3 Punkte, Multiplier 1 Punkt.

**Comment by Ferdie9000** [comment]
danke 

 

 
 

Gesendet: Mittwoch, 03. Februar 2021 um 10:28 Uhr
Von: "Louis Krumme" <notifications@github.com>
An: "markxoe/ich-bin-eine-biene-mobile" <ich-bin-eine-biene-mobile@noreply.github.com>
Cc: "Ferdie9000" <wender.paul@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [markxoe/ich-bin-eine-biene-mobile] Punktanzeige (#25)


 

Hab eingekauft und danach wieder meinen Punktestand angeguckt: Biene 3 Pukte, Multiplier 1 Punkt.
