### ISSUE TITLE
Goldene Biene 

### ISSUE THREAD

**Issue by Ferdie9000** [markxoe/ich-bin-eine-biene-mobile#27]
Wie viele goldene Bienen kann man kaufen?

**Comment by markxoe** [comment]
Unendlich (theoretisch)

**Comment by Ferdie9000** [comment]
ich habe zurzeit 6050 multiplier und kriege trozdem nicht die 2. goldene biene obwohl der preis gleich plebt und ich die 1. goldene biene mit 7010 multiplier bekomen habe

 

 
 

Gesendet: Montag, 08. Februar 2021 um 08:31 Uhr
Von: "Mark Oude Elberink" <notifications@github.com>
An: "markxoe/ich-bin-eine-biene-mobile" <ich-bin-eine-biene-mobile@noreply.github.com>
Cc: "Ferdie9000" <wender.paul@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [markxoe/ich-bin-eine-biene-mobile] Goldene Biene (#27)


 

Unendlich (theoretisch)

**Comment by Ferdie9000** [comment]
ich habe zurzeit 6050 multiplier und kriege trozdem nicht die 2. goldene biene obwohl der preis gleich pleibt und ich die 1. goldene biene mit 5710( hatte ich) multiplier bekomen habe
 

Gesendet: Montag, 08. Februar 2021 um 08:31 Uhr
Von: "Mark Oude Elberink" <notifications@github.com>
An: "markxoe/ich-bin-eine-biene-mobile" <ich-bin-eine-biene-mobile@noreply.github.com>
Cc: "Ferdie9000" <wender.paul@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [markxoe/ich-bin-eine-biene-mobile] Goldene Biene (#27)


 

Unendlich (theoretisch)

**Comment by markxoe** [comment]
Die goldene Biene ist unabhängig von den Multipliern. Wie man im Store sehen kann, kostet die goldene Biene 69420000000000 Saltos

**Comment by Ferdie9000** [comment]
ich hatte bei der 1. goldene biene die app über nacht laufen lassen und hatte am nächsten morgen 30% von der glodenen biene und jetz t habe ich mehr multiplier und habe nichtmal 1% .

könnte es sein das man auch bienen bruacht zu den auto drehern oder nicht weil eigentlich drehen sich ja nur dir autodreher.

 
 

Gesendet: Montag, 08. Februar 2021 um 09:35 Uhr
Von: "Mark Oude Elberink" <notifications@github.com>
An: "markxoe/ich-bin-eine-biene-mobile" <ich-bin-eine-biene-mobile@noreply.github.com>
Cc: "Ferdie9000" <wender.paul@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [markxoe/ich-bin-eine-biene-mobile] Goldene Biene (#27)


 

Die goldene Biene ist unabhängig von den Multipliern. Wie man im Store sehen kann, kostet die goldene Biene 69420000000000 Saltos

**Comment by markxoe** [comment]
Ja, man braucht auch Bienen. 2 Autodreher-umdrehungen sind wie 1 Klick auf eine Biene

**Comment by Ferdie9000** [comment]
Also reicht es nicht aus wenn ich nur autodreher und multiplier kaufe, sonder ich muss nich bienen kaufen damit die autodreher mehr saltos kriegen

 


Gesendet: Montag, 08. Februar 2021 um 10:28 Uhr
Von: "Mark Oude Elberink" <notifications@github.com>
An: "markxoe/ich-bin-eine-biene-mobile" <ich-bin-eine-biene-mobile@noreply.github.com>
Cc: "Ferdie9000" <wender.paul@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [markxoe/ich-bin-eine-biene-mobile] Goldene Biene (#27)


 

Ja, man braucht auch Bienen. 2 Autodreher-umdrehungen sind wie 1 Klick auf eine Biene

**Comment by markxoe** [comment]
Ja
