### ISSUE TITLE
[Idee] Discord Server

### ISSUE THREAD

**Issue by Ferdie9000** [markxoe/ich-bin-eine-biene-mobile#29]
**Allgemeine Beschreibung**
Discord Server 
**Genaue Beschreibung**
Könnten Sie einen Discord Server für Ich bin eijne Biene zu machen wo man selbst bivmal schreiben kann und anderen helfen kann
**Code** (Falls du was hast)
```
```

**Comment by markxoe** [comment]
Halli hallo,
Der Server war noch nicht öffentlich, aber juhu jetzt ist er es!
Hier der Link: https://discord.gg/fh3sVAtrB9
(Kommt noch ins Readme.md)
