### ISSUE TITLE
Bienen buggen weg 

### ISSUE THREAD

**Issue by Ferdie9000** [markxoe/ich-bin-eine-biene-mobile#5]
Ich hatte 10 Auto Dreh binnen und habe dann die App geschlossen als ich wieder reingegangen bin hatte ich nur noch vier

**Comment by markxoe** [comment]
Die Daten werden nur alle 3 Sekunden gespeichert, hast du vielleicht die Autodreher gekauft und dann direkt die App verlassen?
Die ausgegebenen Saltos sollten noch da sein, ist das bei dir auch so?

Oder deine Zeit verstellt?

**Comment by Ferdie9000** [comment]
Ich war jetz den Tag lang rang 18 habe dann das Spiel verlassen und jetz habe ich noch 18 saltos und 3 autodreher und ich glaube 10 Bienen

**Comment by Ferdie9000** [comment]
> Ich war jetz den Tag lang klingelte 18 habe dann das Spiel verloren und jetz habe ich noch 18 saltos und 3 autodreher und ich glaube 10 Bienen

Also ich verliere immer fast alles und das ist jetz schon 2 mal passiert. 
Also immer wenn ich die app geschlossen habe

**Comment by markxoe** [comment]
Sicher? Dieser Fehler kam bisher nur bei Leuten, die versucht haben zu cheaten. Hast du die Zeit ggf nach vorne gestellt? Dann deinstalliere die App und installiere sie wieder.

**Comment by Ferdie9000** [comment]
> Sicher? Dieser Fehler kam bisher nur bei Leuten, die versucht haben zu cheaten. Hast du die Zeit ggf nach vorne gestellt? Dann deinstalliere die App und installiere sie wieder.

Ich werde es versuchen

**Comment by markxoe** [comment]
> 
> 
> > Sicher? Dieser Fehler kam bisher nur bei Leuten, die versucht haben zu cheaten. Hast du die Zeit ggf nach vorne gestellt? Dann deinstalliere die App und installiere sie wieder.
> 
> Ich werde es versuchen

Frage: Hattest du versucht zu Cheaten? Hat deinstallieren funktioniert? Hätte sowieso nicht funktioniert 😀, aber Datenverlust kann dabei leider nicht rückgänging gemacht werden...

**Comment by markxoe** [comment]
Ein Bug wurde gefunden wie schon in #12 geschrieben. Patch kommt hoffentlich heute noch
