### ISSUE TITLE
Ban-Feature 

### ISSUE THREAD

**Issue by moritzlerch** [markxoe/ich-bin-eine-biene-mobile#9]
User-Daten mit Begründung löschen

**Comment by markxoe** [comment]
Gute Idee!

**Comment by ghost** [comment]
Wie ist das gemeint?

**Comment by moritzlerch** [comment]
@kevnhuck 
> Wie ist das gemeint?

naja, einfach, wenn jemand Scheiße baut, dass man dann die User-Daten löschen kann

**Comment by ghost** [comment]
Ja, aber wie soll man da scheisse bauen?

**Comment by moritzlerch** [comment]
Das kannst du dir gerne selber überlegen 👀

**Comment by markxoe** [comment]
Ist jetzt implementiert 👍🏻

**Comment by moritzlerch** [comment]
Nice!
